### ISSUE TITLE
Move to GlobalFishingWatch org

### ISSUE THREAD

**Issue by geowurster** [GlobalFishingWatch/gcs-proxy#1]
This relates much more to GFW than to SkyTruth, so lets put it there.

/ cc @enriquetuya

**Comment by redhog** [comment]
What do you mean? This needs to be it's own Google project to work. You can't have multiple GAE projects within one google project.

**Comment by geowurster** [comment]
@redhog No I mean move to the GFW GitHub org.

**Comment by redhog** [comment]
Ah... Sure.

**Comment by redhog** [comment]
Done. Unfortunately the move meant that now I don't have admin rights for the repo any more. Do you @geowurster ? Could you add me back?

**Comment by geowurster** [comment]
@redhog Fixed.

**Comment by redhog** [comment]
@geowurster I still can't see any "settings" icon on the repository page...

**Comment by geowurster** [comment]
@redhog Weird - looks like you inherited the old permissions?  Try it now.

**Comment by redhog** [comment]
Ah, now it works. Thanks!
